name: SkySimEngine
version: 1.0-SNAPSHOT
main: in.godspunky.skyblock.SkySimEngine
authors: [ GiaKhanhVN ]
description: this is a description, what do you want from me

softdepend: [PlaceholderAPI]
depend: [LibsDisguises, Multiverse-Core, ProtocolLib]
commands:
  setrank:

